# ── Metadata ─────────────────────────────
id = "board-syntax"
name = "Board Syntax"
version = "0.0.0"
schema_version = 1
authors = ["TugaLaTurtuga <TugaLaTurtuga@gmail.com>"]
description = "Syntax highlighting for .board task files"
repository = "https://github.com/TugaLaTurtuga/board-syntax-zed"
languages = ["Board"]
tags = ["Language"]

[grammars.board]
repository = "https://github.com/TugaLaTurtuga/tree-sitter-board"
rev = "c3098b997a8628d6685a839db83be8b1fee4e847"
